### ISSUE TITLE
How avox define which env must be used?

### ISSUE THREAD

**Issue by worldmind** [astronouth7303/xontrib-avox#4]
I am sorry, but I can't understood from readme how avox define which env must be used in concrete dir?
For example, I create virtualenv named `django11` via vox, create project directory `djtest`. How say to avox that after `cd` to `djtest` is must activate `django11` env?

**Comment by AstraLuma** [comment]
avox uses vox-managed virtual environments, where the project directory name matches the venv name.

For example, if you've set `$PROJECT_DIRS = ["~/code"]` and have the project directory `~/code/spam`, avox will use the venv name `spam`.

This is the only policy that will ever be supported by avox, by design. If this is not suitable for you, I heartily support blatently copying the code and making your own project with your own ideas of how projects should map to environments.

**Comment by worldmind** [comment]
@astronouth7303 thanks for explanation, I think this phrase:

> For example, if you've set $PROJECT_DIRS = ["~/code"] and have the project directory ~/code/spam, avox will use the venv name spam.

needed to be in README
